### ISSUE TITLE
Beam Size in Choice and BaseChoice

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#11]
Both `BaseChoice` and `Choice` have the parameter `beam_size`, which causes the following error when building a `Choice` layer:
`TypeError: __init__() missing 1 required keyword-only argument: 'beam_size'`

From reading the code, I would suggest removing beam_size from the `Choice` layer (class), since other classes inheriting from `BaseChoice` might also need it. What do you think?

Also how would you handle this? Make an exception in the `_generate_layers` script or is there a better way? 
I can make a PR once we decided on a good solution.

**Comment by albertz** [comment]
This could be similarly handled as I suggested in #12. I.e. detect this more automatically. We would need to find and parse the super(...).__init__(...) call in the code, and there we could see that `beam_size=beam_size`, and we would replicate that in the generated code.

**Comment by albertz** [comment]
Fixed via #14.
