### ISSUE TITLE
nn.normalize without scale and bias

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#188]
I just noticed that the current implementation of `nn.normalize` does not have the option to add scale and bias. 
In general this of course can be added by the user by
```python
x = nn.normalize(x, axis=x.feature_dim)
bias = nn.Parameter(list(x.shape), trainable=True)
scale = nn.Parameter(list(x.shape), trainable=True)
x = scale * x + bias
```

Still this is different from how its implemented in Returnn, so I wanted to bring this up for discussion whether it makes sense to either document this in `nn.normalize` or actually implement it.

**Comment by albertz** [comment]
I guess we can consider this as closed via #190.
