### ISSUE TITLE
mark_as_loss with mandatory name arg?

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn_common#207]
Currently the loss name is very arbitrary, and also not stable, i.e. it could potentially change depending on other unrelated things in the model, or if we do some internal changes, so you can never rely on that whatever name you get there stays always the same (as for all layer names).

This is bad for the loss, as the loss is also used for logging, for LR scheduling (and you do the LR schedule by loss name), etc.

So we can introduce a name arg. Should we even make that mandatory?

**Comment by Atticus1806** [comment]
I like the idea of introducing a name. This would make reading logs a lot easier imo.

Regarding the mandatory part I dont have a strong oppinion, but would not mind it too much (fix is quite easy for existing networks)

**Comment by albertz** [comment]
Ok, done.
