### ISSUE TITLE
Matching Tensors still require explicit `allow_broadcast_all_sources`

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn_common#222]
The message is:
```python
ValueError: combine: sources [<Tensor /'nartts_model'/'duration'/'log'/'_activation'/'log' [B,T|'phon_labels_time'[B],F|F'pred_lin_dim'(1)] via 'activation'>, <Tensor /'nartts_model'/'cast' [B,T|'phon_labels_time'[B],F|F'phon_durations_feature'(1)] via 'cast'>] require explicit allow_broadcast_all_sources=True
```
So both are [B,T,1] with the same B and the same T, just a different Dim for F with the same size. I would have assumed this is okay, and in former `returnn_common` versions this was still fine. So is this an error or the new expected behavior?

**Comment by albertz** [comment]
No they are not the same. `F'pred_lin_dim'(1)` is not the same as `F'phon_durations_feature'(1)`. It was never the same since we have dimension tags. So I don't think that this worked in former `returnn_common` or RETURNN versions. There was probably another difference as well.

**Comment by JackTemaki** [comment]
Okay, then it does not make sense to look for what changed, I will just live with the new (now correct) behavior and alter my network.
