### ISSUE TITLE
GenericSelfAttention, biases are inconsistent to SelfAttentionLayer

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn_common#234]
I noticed that the `nn.SelfAttention` is a bit different to `SelfAttentionLayer`: `SelfAttentionLayer` does not have biases for the `qkv` and `proj` linear projections, while `nn.SelfAttention` currently has.

This is relevant for Conformer (e.g. #233) and Transformer.

**Comment by albertz** [comment]
Well, maybe having those biases is actually standard? E.g. In Fairseq:
https://github.com/facebookresearch/fairseq/blob/b4001184f49ed0e20d619b54bb3d43088fabf990/fairseq/modules/multihead_attention.py#L123-L131

**Comment by albertz** [comment]
Also used by default in PyTorch `nn.MultiheadAttention` (https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html#torch.nn.MultiheadAttention).

**Comment by albertz** [comment]
Note that `SelfAttentionLayer` was designed 1:1 to be equivalent to the Tensor2Tensor code, and also looking at the current T2T code (I think [here](https://github.com/tensorflow/tensor2tensor/blob/384d527cbef3e3917f52a22f6892c5ea4cb125fd/tensor2tensor/layers/common_attention.py#L4370)), it seems there is no bias there. So that was the original Transformer. But since then, it has evolved, and I think Fairseq is probably much more used.

**Comment by albertz** [comment]
In ESPNet, bias is also used:
https://github.com/espnet/espnet/blob/a65cc78de7e18c867f4be5fc0b9b695875c78c70/espnet/nets/pytorch_backend/transformer/attention.py#L32-L34

**Comment by albertz** [comment]
So, as they seem to be standard nowadays, I think having them enabled is ok.

**Comment by albertz** [comment]
@patrick-wilken Are you aware of this?

**Comment by albertz** [comment]
I added the option `with_bias`, so you can specify it explicitly. The default is still True now.

**Comment by patrick-wilken** [comment]
No, I wasn't. You won't find papers discussing what difference it makes, right? Maybe I should try it out, bias seems like well spent parameters. 😄

**Comment by albertz** [comment]
Note that this `with_bias` was added to returnn-common. It's not available in `SelfAttentionLayer`.
