### ISSUE TITLE
Cond wrapper

### ISSUE THREAD

**Issue by albertz** [rwth-i6/returnn_common#24]
Similar as #23, some API with `with Cond(...) as cond_obj:`, which corresponds to `if ...:`, and then some further `with cond_obj.false_branch():`, which corresponds to the `else:` branch.

Example:
```
x = ... # whatever
cond = ...  # scalar tensor, True or False
with Cond(cond) as cond_obj:
  y = mod_true_case(x)
with cond_obj.false_branch():
  y = mod_false_case(x)
```

But this is not so clear yet.

**Comment by albertz** [comment]
> ```
> x = ... # whatever
> cond = ...  # scalar tensor, True or False
> with Cond(cond) as cond_obj:
>   y = mod_true_case(x)
> with cond_obj.false_branch():
>   y = mod_false_case(x)
> ```

The example cannot work like this because it requires that we know about the Python local variable name, which we do not.

We need to specifically connect both the true-case value and the false-case value such that RETURNN can make it the same layer name.

Maybe just disallow to directly access `y` now outside the scope so this cannot be used accidentally like this.

And then requite sth like:
```
x = ... # whatever
cond = ...  # scalar tensor, True or False
with Cond(cond) as cond_obj:
  y_true = mod_true_case(x)
with cond_obj.false_branch():
  y_false = mod_false_case(x)
  y = cond_obj.output(y_true, y_false)
```
So all outputs have to be passed through `Cond.output` explicitly, and combine the true-branch value with the false-branch value.

**Comment by JackTemaki** [comment]
In the way it is written here it seems for me it is more complicated than necessary, because in the end you could reduce it just to:
```python
x = ... # whatever
cond = ...  # scalar tensor, True or False
y_true = mod_true_case(x)
y_false = mod_false_case(x)
y = Cond(cond, y_true, y_false)
```
Which looks somewhat simpler but has the same expressiveness. As long as there is no possibility for syntax that directly looks like how `if` and `else` look like, I think it is easier to stick to something like this.

**Comment by albertz** [comment]
No, it cannot work like that, because it has to be inside some special scope, because you don't want to execute both `mod_true_case` and `mod_false_case` as it would be the case in your example (also if this would be equivalent PyTorch code).

**Comment by albertz** [comment]
Another API suggestion (draft):
```
with Cond(cond) as cond_obj:
  y = mod_true_case(x)
  cond_obj.else()
  y = mod_true_case(x)
```

In both the original suggestion and this draft, we have the problem that the first `y` would be marked as unused, and also it is not really defined that this is the output.

So, maybe:
```
with Cond(cond) as cond_obj:
  y = mod_true_case(x)
  cond_obj.else(y)
  y = mod_true_case(x)
  y = cond_obj.end(y)
```

The arguments to `else` and `end` would define the outputs of the true and false branch, and the returned value of `end` would yield the layer ref(s) which can be used outside.

**Comment by albertz** [comment]
Should this `Cond` generalize to the case that `cond` is not a scalar? In that case, it would wrap `tf.where`.
