### ISSUE TITLE
Multiple returns doesn't use output layer

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#26]
When returning multiple layers, referencing these layers causes all of them in the returnn config to be used with the sublay name with `/` instead of one (the first one) being used with just the subnetwork name (to reference the output layer). This then causes an issue when starting returnn, since returnn does not find the output layer in the subnetwork. I guess this happens cause optimized away since its not used. Setting one of them to the output layer by hand fixes this issue. There might be an easy returnn_common fix for this, but right now I dont have the time to look into it so I will leave this issue already, maybe you see and easy fix.

An example (which maybe when fixed can also be changed into a test) would be: 

```
class SubSub(Module):

  def __init__(self):
    super().__init__()
    self.linear = layers.Linear(n_out=2)

  def forward(self, x: LayerRef) -> LayerRef:
    lin1 = self.linear(x)
    lin2 = self.linear(lin1)
    return lin1, lin2


class Sub(Module):
  def __init__(self):
    super().__init__()
    self.linear = layers.Linear(n_out=3)
    self.sub = SubSub()

  def forward(self) -> LayerRef:
    data = get_extern_data("x")
    lin1, lin2 = self.sub(data)
    lin3 = self.linear([lin1, lin2])
    return lin3
```
produces the following config, where you can see that jsut `linear` and `linear_0` in `from` are used but never `sub`
```
{'sub': {'class': 'subnetwork', 
           'from': [], 'subnetwork': {'linear': {'class': 'linear', 'from': 'base:data:x', 'n_out': 2},
                                      'linear_0': {'class': 'linear', 'from': 'linear', 'n_out': 2, 'reuse_params': 'linear'}, 
                                      'output': {'class': 'copy', 'from': 'linear'}}}, 
 'linear': {'class': 'linear', 'from': ['sub/linear', 'sub/linear_0'], 'n_out': 3},
 'output': {'class': 'copy', 'from': 'linear'}}

**Comment by albertz** [comment]
First of all, this sounds like a bug in RETURNN itself. This net dict should work in any case. (So you should open a separate issue in the RETURNN repo about this.)

So returnn-common is not wrong here. It's just a matter of preference/taste. I think when you use a single output, it already uses the main layer output (just `sub` here). So you think, for multiple outputs, the first one should become the main subnet output (it is already, but just for completeness, because I think RETURNN requires some `output` layer in a subnet in any case, not sure), and the layer ref should use the subnet layer output itself instead of the sub layer?

**Comment by Atticus1806** [comment]
> First of all, this sounds like a bug in RETURNN itself. 

I feel like its more of convention. If we force the subnetwork to have a used output layer, which as far as I know we do right now, then this is not really a bug. If you say this should work though, I can open an issue there and we talk about the implications for RETURNN sure. I am not 100% if this is really an issue of RETURNN so I will wait with that for now, but if we agree on making changes in RETURNN or this being a RETURNN issue I will open something there.

>I think when you use a single output, it already uses the main layer output (just sub here)

Yes this is just not happening for multiple returns. Single return is working fine.

>RETURNN requires some output layer in a subnet in any case, not sure

also yes, that is whats causing the issue most likely, since that layer, even though its in the config, is never used thus optimized away I think.

>So you think, for multiple outputs, the first one should become the main subnet output and the layer ref should use the subnet layer output itself instead of the sub layer?

That would be one way (and my suggestion) to go about it. So right now the output layer gets set to the first return of the function, which I think makes sense. What we could do here is either change in returnn_common that the first returned layer also then is used in a way that the output is used (like in the single layer case) or the other way would be to change RETURNN in a way that we a) dont require an output layer or b) have returnn never optimize these layers.

**Comment by albertz** [comment]
> > First of all, this sounds like a bug in RETURNN itself.
> 
> I feel like its more of convention.

Conventions should be irrelevant for the question whether it should work or not.

> If we force the subnetwork to have a used output layer, which as far as I know we do right now,

I'm not sure if we do. And if we do, maybe this is another thing which should be fixed, which should not be forced?

But even if we do and leave it, I don't see how that would invalidate what I argued before, that the net dict should work in any case. So I think this is also irrelevant.

> If you say this should work though, I can open an issue there and we talk about the implications for RETURNN sure. I am not 100% if this is really an issue of RETURNN ...

I'm almost 100% sure this is a bug in RETURNN.

> > RETURNN requires some output layer in a subnet in any case, not sure
> 
> also yes, that is whats causing the issue most likely, since that layer, even though its in the config, is never used thus optimized away I think.

No, I don't think so. That's not how subnetworks work. A subnetwork is not even a layer at all (anymore). The `SubnetworkLayer` is just the interface/API to the subnetwork system. It's basically just a namespace. But anyway, let's debug and find out. And discuss further on RETURNN side.

> > So you think, for multiple outputs, the first one should become the main subnet output and the layer ref should use the subnet layer output itself instead of the sub layer?
> 
> That would be one way (and my suggestion) to go about it. So right now the output layer gets set to the first return of the function, which I think makes sense. What we could do here is either change in returnn_common that the first returned layer also then is used in a way that the output is used (like in the single layer case) or the other way would be to change RETURNN in a way that we a) dont require an output layer or b) have returnn never optimize these layers.

Let's separate the two questions (1: main output in subnet layer; 2: what layer ref should point to).

For 2, I actually think what it does right now is cleaner (for the case of multiple returns).

For 1, I guess it is already as you expect. Although I would maybe even remove that (if possible, and if we keep point 2 as it is). But changing this would be a separate thing.

**Comment by Atticus1806** [comment]
>For 2, I actually think what it does right now is cleaner (for the case of multiple returns).
For 1, I guess it is already as you expect. Although I would maybe even remove that (if possible, and if we keep point 2 as it is). But changing this would be a separate thing.

In general I agree with you: Actually the more I think about it, I am not even sure wether I like implicitly referencing the output layer via referencing the subnetwork at all. Of course its shorter, but it always hides some part of the structure when reading the config, since the subnetwork output might not be 100% clear all the time. But then again, I think changing it for "single case" might make the config also more messy, since the layer names might become longer, and if we have some generic names, like `linear_0`, `linear_1` etc. just seeing `linear_block/linear_x` instead of `linear_block` for single output might not really give more information. What do you think?

**Comment by albertz** [comment]
My reasoning for the single output case was: When you have a single output, this is non-ambiguously meant to be the "main" output. So this is what the module computes. The module is the subnetwork layer in RETURNN. So the subnetwork layer has this main output.

**Comment by albertz** [comment]
So it sounds like you kind of agree that it's ok like it is right now (on returnn-common side). So then we can close this.
