### ISSUE TITLE
RecUnit additional parameters

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#5]
Currently the class Rec is missing the possibility to add additonal parameters like max_seq_len i think. Maybe through modifying `_make_layer_dict_from_subnet_ctx` through adding an additional dict for additional params?

**Comment by albertz** [comment]
What do you mean? `RecUnit` has all those params.

Although RecUnit is anyway only supposed to be used for fixed `unit` types (lstm etc), for some input, where args like `max_seq_len` are not needed.

Or you mean the `Rec` module, based on `ISubnet`? Yes, this should be extended by those needed args.

**Comment by albertz** [comment]
I didn't really tested anything of this yet. I pushed some update to `Rec`.
