### ISSUE TITLE
`LSTM` is missing `direction` option

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn_common#88]
I did not look into the implementation details yet, but the `direction=-1` feature seems to be completely missing. I am not sure how this should look like in the new interface, but it needs to exist.

**Comment by albertz** [comment]
`_Rec` is internal API, so this should not matter, as the user should not use `_Rec`. And I currently plan to rewrite all of this.

You probably mean `LSTM` or maybe `ZoneoutLSTM`? (I also plan to rewrite `ZoneoutLSTM`.)

**Comment by JackTemaki** [comment]
Yes sure it is internal, I am just saying that everything that will derive from this misses this feature, as do `LSTM` and `ZoneoutLSTM`.

**Comment by JackTemaki** [comment]
Solved with 44da59511ea6577d2908fee33452da906ec77a67
