### ISSUE TITLE
Loss Scale

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#9]
So as I understand right now, we want to go away from using `Returnn` Losses and use Loss `'as_is'`. How would adding a loss scale be intended here? Use a mult layer with a constant? Or is there a better way or not implemented yet? Maybe add a parameter to the `mark_as_loss()` function with default value 1?

**Comment by albertz** [comment]
> How would adding a loss scale be intended here?

I have not thought about this yet.

> Use a mult layer with a constant?

Yea, this is one way which is always possible of course. But not sure if the best way. (Although, I think this would most closely match how you would do it in PyTorch.)

> Or is there a better way or not implemented yet?

You know what is implemented. :) But in any case, if sth is not implemented, we can always simply just implement it.

> Maybe add a parameter to the `mark_as_loss()` function with default value 1?

Yea, that is also a good idea. PR is welcome.

**Comment by Atticus1806** [comment]
Just opened a PR.

>You know what is implemented. :)

Yes you are right, I should know or can read it up, sometimes I am not sure wether I overlooked something. But I guess in `returnn_common` since its quite new and not really used yet I can safely assume that if I dont find something it is not there yet. :)

**Comment by Atticus1806** [comment]
I will close this now, we can discuss any changes in the PR itself I guess.

**Comment by albertz** [comment]
> I will close this now, we can discuss any changes in the PR itself I guess.

An issue should only be closed once the issue/bug is really resolved/fixed. E.g. when a corresponding PR is merged.

A PR (or commit) can also automatically close an issue when you write sth like "Fix #9" in its description.
